name: Deploy to EC2

on: 
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: SSH into EC2 and execute commands
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{secrets.EC2_USERNAME }}
              key: ${{ secrets.EC2_PRIVATEKEY}}
              script: |
                cd /var/www
                sudo -rm -rf html
                sudo mkdir html
                sudo git clone https://github.com/Ivanlr96/prueba-git-actions
                sudo syste, restart nginx